openapi: 3.0.0
info:
  title: Turing API developed by Meshack Mbuvi
  summary: API endpoints for Ggebeya marketplace exam
  description: Nodejs backend for Gebeya marketplace exam

version: 0.1.9

servers:
  - url: http://localhost:3000/api

components:
  securitySchemes:
    USER-KEY:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Item:
      type: object
      properties:
        product_id:
          type: number
          example: 1
        name:
          type: string
          example: banana
        description:
          type: string
          example: "product description"
        price:
          type: number
        photo:
          type: string
        vendorName:
            type: string
    Items:
      type: array
      items:
        $ref: '#components/schemas/Item'
    
    User:
      type: object
      properties:
        user_id:
          type: string
          example: 1
        name:
          type: string
        email:
          type: string
        password:
            type: string
paths:
  /items:
    get:
      summary: Retrieve all items
      description: Retrieve all products from api
      tags:
        - Products
      parameters:
        - in: query
          name: page
          schema:
            type: integer
          description: Inform the page. Starting with 1. Default: 1
        - in: query
          name: limit
          schema:
            type: integer
          description: Limit per page, Default: 20.
        - in: query
          name: description_length
          schema:
            type: integer
          description: Limit of the description, Default: 200.
      responses:
        200:
          description: Get All Products
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: number
                    example: 40
                  rows:
                    $ref: '#components/schemas/Products'
  